name: Build Storybook

on:
  pull_request:
    branches:
      - master

jobs:
  Build-Storybook:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Install dependencies
      run: yarn
    - name: Build components
      run: yarn run build
    - name: Build Storybook
      run: yarn run build-storybook
    - name: Deploy Storybook
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
