name: Build Storybook

on:
  pull_request:
    branches:
      - master

jobs:
  Build Storybook:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Install dependencies
      run: yarn
    - name: Build components
      run: yarn run build
    - name: Build Storybook
      run: yarn run build-storybook
