name: Build Storybook

on:
  pull_request:
    branches:
      - master

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Install dependencies
      run: yarn
    - name: Build storybook
      run: yarn run build-storybook
